### ISSUE TITLE
Why I won't submit this as Pull Request to AimTuxOfficial or LWSS

### ISSUE THREAD

**Issue by mellowagain** [Marc3842h/Fuzion-Hotpatcher#1]
Simply because the code is shit. I'm unexperienced in C and C++ and this shouldn't be merged into a good and living project (oh well, how ironic looking at you AimTux). 

**Also it isn't even proven its gdb that causes the Untrusted Bans.**

The branch `upstream-merge` has been created if I ever am going to merge this into the upstream (most likely won't happen as Valve is surely watching the upstream for changes)

**Comment by LWSS** [comment]
ur waifu a shite

**Comment by Marc3842h** [comment]
@LWSS If you fix the shitty code you can merge it into your fork idc tbh

**Comment by mellowagain** [comment]
**Fuzion-Hotpatcher has been detected, not going to merge because of obvious reasons.**

**Comment by dexter-spigot** [comment]
Is it really detected?

**Comment by mellowagain** [comment]
If my previous reply wasn't clear enough, nothing but testing will make it more clear.
