### ISSUE TITLE
I have this error on hotpatch - make install

### ISSUE THREAD

**Issue by brunopayne** [Marc3842h/Fuzion-Hotpatcher#2]
easycheats@easycheats-desktop ~/Desktop/hotpatch $ make install
[ 20%] Built target hotpatch
[ 40%] Built target hotpatch_s
[ 50%] Built target hotpatcher
[ 60%] Built target hotpatchtest
[ 70%] Built target compiletestcpp
[ 80%] Built target dummy
[ 90%] Built target loadertest
[100%] Built target compiletestc
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/include/hotpatch.h
CMake Error at include/cmake_install.cmake:36 (file):
  file INSTALL cannot copy file
  "/home/easycheats/Desktop/hotpatch/include/hotpatch.h" to
  "/usr/local/include/hotpatch.h".
Call Stack (most recent call first):
  cmake_install.cmake:37 (include)
  

Makefile:71: recipe for target 'install' failed
make: *** [install] Error 1
easycheats@easycheats-desktop ~/Desktop/hotpatch $

Because this i have an error on injection: The CHEAT not inject !

easycheats@easycheats-desktop ~/Desktop/hotpatch/Fuzion-Hotpatcher $ ./load
sudo: hotpatcher: command not found
Successfully injected using Hotpatcher!
easycheats@easycheats-desktop ~/Desktop/hotpatch/Fuzion-Hotpatcher $

**Comment by mellowagain** [comment]
**`sudo`**` make install`

**Comment by smaranil** [comment]
I successfully complied the fuzion-hotpatcher but when i inject it says
injected but in game i cant see the GUI when i press insert .

Yes i have install hotpach
I am on Arxh linux antergos

**Comment by mellowagain** [comment]
@smaranil Do you have a Fuzion watermark in the corner? Open another issue instead of commenting on another one btw

**Comment by smaranil** [comment]
Yes

**Comment by smaranil** [comment]
Sorry no i dont have the fuzion in game in the corner

**Comment by brunopayne** [comment]
Thanks marc, sudo is a admin comand, i dont remember this. Now its running.
